FROM node:20-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y libssl3

RUN npm install -g pnpm

COPY . .

RUN pnpm install

RUN pnpm prisma generate --schema=apps/api/prisma/schema.prisma

EXPOSE 3000

WORKDIR /app/apps/api

CMD ["npx", "ts-node", "--project", "tsconfig.app.json", "src/main.ts"]