FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY . .

RUN pnpm install

EXPOSE 80

CMD ["pnpm", "nx", "serve", "frontend", "--port", "80", "--host", "0.0.0.0", "--proxy-config", "apps/frontend/proxy.conf.json"]