FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .
RUN pnpm nx build api

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/api/package.json .
COPY --from=builder /app/dist/apps/api .

RUN npm install -g pm2

EXPOSE 3000

CMD ["pm2", "start", "main.js", "--no-daemon"]